# Generated by Django 5.0.6 on 2024-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_manufactured_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="viwes_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
