# Generated by Django 5.0.6 on 2024-08-28 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_version",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Укажите номер версии продукта",
                        null=True,
                        verbose_name="Номер версии",
                    ),
                ),
                ("name_of_version", models.CharField(max_length=255)),
                ("current_version_flag", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
                "ordering": ["-number_of_version"],
                "unique_together": {("product", "number_of_version")},
            },
        ),
    ]
